import { describe, expect, it } from "vitest";
import { SITE_SCHEDULE } from "../site-schedule";
import { WAYPOINTS } from "../waypoints";
import { clampProgress, currentWaypoint, interpLayer } from "../zoom";

describe("depth-as-time: content ordering", () => {
  it("orders waypoints by strictly increasing lookback time", () => {
    for (let i = 1; i < WAYPOINTS.length; i++) {
      expect(WAYPOINTS[i].lookbackYears).toBeGreaterThan(WAYPOINTS[i - 1].lookbackYears);
    }
  });
});

describe("depth-as-time: zoom engine", () => {
  const frames = [
    { t: 0, scale: 2, x: 50, y: 0, opacity: 0 },
    { t: 0.5, scale: 1, x: 0, y: 0, opacity: 1 },
  ];

  it("holds the first keyframe before its progress is reached", () => {
    expect(interpLayer(frames, -1)).toEqual({ scale: 2, x: 50, y: 0, opacity: 0 });
  });

  it("holds the last keyframe past its progress", () => {
    expect(interpLayer(frames, 5)).toEqual({ scale: 1, x: 0, y: 0, opacity: 1 });
  });

  it("linearly interpolates between two keyframes", () => {
    expect(interpLayer(frames, 0.25)).toEqual({ scale: 1.5, x: 25, y: 0, opacity: 0.5 });
  });

  it("clamps progress to [0, 1]", () => {
    expect(clampProgress(-3)).toBe(0);
    expect(clampProgress(3)).toBe(1);
    expect(clampProgress(0.4)).toBe(0.4);
  });

  // `from` is generated by the schedule (site-schedule.ts), not hand-copied
  // here — that's the point of the generator: these tests keep working
  // whatever the actual duration/gap constants are tuned to.
  const staged = WAYPOINTS.map((w) => ({ ...w, from: SITE_SCHEDULE.schedule.from.get(w.id) })).filter(
    (w): w is typeof w & { from: number } => w.from !== undefined,
  );

  it("picks the waypoint whose progress threshold has most recently been crossed", () => {
    expect(currentWaypoint(0, staged).id).toBe(staged[0].id);
    expect(currentWaypoint(1, staged).id).toBe(staged[staged.length - 1].id);
  });

  it("switches to each waypoint exactly at its own settle point, not before", () => {
    for (let i = 1; i < staged.length; i++) {
      expect(currentWaypoint(staged[i].from, staged).id).toBe(staged[i].id);
      expect(currentWaypoint(staged[i].from - 0.0001, staged).id).toBe(staged[i - 1].id);
    }
  });
});
